### ISSUE TITLE
put code access sample

### ISSUE THREAD

**Issue by epogrebnyak** [mini-kep/user-charts#1]
```python 

import pandas as pd

URL = {'a': 'http://mini-kep.herokuapp.com/annual',
    'q': 'http://mini-kep.herokuapp.com/quarterly',
    'm': 'http://mini-kep.herokuapp.com/monthly'}

def read_csv(source):
    return pd.read_csv(source, converters={0: pd.to_datetime}, index_col=0)

dfa, dfq, dfm = (read_csv(URL[freq]) for freq in 'aqm')
```

**Comment by epogrebnyak** [comment]
A. in this issue list parts of code responsible for time series import:
1. type 1 (read csv from stable URL):
  - [ ] from parser-rosstat-kep getter.py
  - [ ] from front-endapp frontpage 
  - [ ] from parser-rosstat-kep readme.md 
Intent: make this code the same in different parts fo project

2. type 2, new end-user pipeline (read csv for):
  - [ ]  user code <https://github.com/mini-kep/db/blob/master/doc/pipeline.py#L75-L94>  
Intent: this code will be used by the user to read from API as:
```annual_CPI_rog = pd.read_json('http://mini-kep.herokuapp.com/ru/series/CPI/a/rog')```
  - [ ]  server code proxy for this (few lines up in pipeline.py)

3. think of quick relay of data from ```parser-rosstat-kep``` into new API (using pandas)

B. not todo now: 
   - [ ] local file caching 
   - [ ] r fork

**Comment by hojimat** [comment]
code sources are:
A1.1. https://github.com/mini-kep/parser-rosstat-kep/blob/master/src/getter.py
A1.2. https://github.com/mini-kep/frontend-app/blob/master/apps/templates/home.md
A1.3. https://github.com/mini-kep/parser-rosstat-kep/blob/master/README.md

**Comment by epogrebnyak** [comment]
In A1 we want ot ensure ```read_csv()``` is the same everywhere. That seems to hold, but it was not true all the time before.In a single codebase this would have been a helper func for all other modules.
In A2 we want a code that the user willl use to get data from API and server code example that generates it. @ravshansk - can you extract the A2?

**Comment by epogrebnyak** [comment]
@ravshansk - are you up to this? without A2 cannot really do point 3.

**Comment by epogrebnyak** [comment]
Code listings used at <https://github.com/mini-kep/intro/blob/master/datamodel_and_api.md>

**Comment by epogrebnyak** [comment]
interface examples:
- [ ] interface.r (based on src/getter.py)
- [ ] interface.py
- [ ] quandl.py
- [ ] fred.py

**Comment by epogrebnyak** [comment]
Closed by <https://github.com/mini-kep/user-charts/blob/master/access.py>
